### PR TITLE
Servant 0.18 and increase upper bounds [CircuitHub's PR #43 rebased on latest `master`]

### PR DESCRIPTION
**Pull request by kahlil29**

### CODE REVIEW

**Comment by kahlil29** [comment]
@ocharles 
We can either merge this PR or you can add commit beb9f11 to your original PR and then we can go ahead and merge it. 
I'm okay with either, let me know your preference 😄

**Comment by ocharles** [comment]
Please go ahead and do what you want, I unfortunately don't have time to do more on this I'm afraid!

**Comment by kahlil29** [comment]
Okay, no worries. 
I don't think I can commit/push to the other PR since the branch is from CircuitHub's fork, but I'll just go ahead and merge this 😄  
Do let me know if there are any other changes, updates or enhancements you'd like to see for this project & I can try my best to implement them 👍🏻

**Comment by ocharles** [comment]
Sounds good! Thanks folks :smiley:

**Comment by ocharles** [comment]
@kahlil29 Thanks for all of this work. The last piece of the puzzle would be to upload to Hackage - could you do that?

**Comment by kahlil29** [comment]
@ocharles Sure, will do. Should be done early next week 👍🏻

**Comment by kahlil29** [comment]
@ocharles Released version `0.1.3` to Hackage. 
I'm not familiar with doing these releases so had to do a couple to (hopefully) get it right. 
Do let me know if something does not look right and I'll fix it.

**Pull request merged**
